package com.framgia.fel1.constant;

/**
 * Created by vuduychuong1994 on 4/19/16.
 */
public interface Const {
    int PASSWORD_MIN_LENGTH = 5;
    String ID = "id";
    String ACTIVITIES = "activities";
    String CONTENT = "content";
    String CREATED_AT = "created_at";
    String IS_CORRECT = "is_correct";
    String CATEGORIES = "categories";
    String NAME = "name";
    String PHOTO = "photo";
    String LEARNED_WORDS = "learned_words";
    String TOTAL_PAGES = "total_pages";
    String RESULT_ID = "result_id";
    String ANSWERS = "answers";
    String LESSON = "lesson";
    String WORDS = "words";
    String USER = "user";
    String EMAIL = "email";
    String AVATAR = "avatar";
    String ADMIN = "admin";
    String AUTH_TOKEN = "auth_token";
    String UPDATED_AT = "updated_at";
    String PASSWORD = "password";
    String PASSWORD_CONFIRMATION = "password_confirmation";
    String MESSAGE = "message";
    int ACTION_PICK_IMAGE = 2324;
    String IMAGE_TYPE = "image/*";
    String WORD = "word";
    int COUNT_LESSON = 50;
    int MAX_COUNT_WORDS = 97;
    int POSITION_ANSWER_1 = 0;
    int POSITION_ANSWER_2 = 1;
    int POSITION_ANSWER_3 = 2;
    int POSITION_ANSWER_4 = 3;
    String CATEGORY_ID = "category_id";
    String OPTION = "option";
    String ALL_WORD = "all_word";
    String ANSWER = "Answer";
    String CATEGORY = "category";
    int COLUMN_WORD_LIST = 2;
    String LEARNED = "learned";
    String NO_LEARN = "no_learn";
    String LESSON_ID = "lesson_id";
    String MY_PREFERENCE = "preference";
    String REMEMBER = "remember";
    String JSON_TYPE = ".json";
    String PER_PAGE = "per_page";
    int DEFAULT_PERPAGE_WORDLIST = 20;
    String PAGE = "page";
    String ANSWER_ID = "answer_id";
    String RESULT_ATTRIBUTES = "results_attributes";
    String URL_UPDATE_LESSON = "https://manh-nt.herokuapp.com/lessons/";
    String CONTENT_LOADING = "content_loading";
    int MY_PERMISSIONS_REQUEST_WRITE_STORAGE = 543;
    String ANSWER_TAG = "answer_tag";
    String LIST = "list";
    String LESSON_ANS = "lesson_ans";
    String ISLESSON = "ISLESSON";
    String FILTER_ALL_WORDS = "all_word";
    String FILTER_NEW_WORDS = "no_learn";
    String FILTER_LEARNED_WORDS = "learned";
    String PATH_LESSON = "/lessons.json";
    int DEFAULT_REQ = 100;
}
